let musicarr = [
    {
        id:980145801,
        name:'海边',
        img:require('@/assets/img/musicRadio/haibian.webp'),
        color:'#3585cf'
    },
    {
        id:977552564,
        name:'学习',
        img:require('@/assets/img/musicRadio/xuexi.webp'),
        color:'#537b92'
    },
    {
        id:527520656,
        name:'清凉',
        img:require('@/assets/img/musicRadio/qingliang.webp'),
        color:'#6bbea5'
    },
    {
        id:977456480,
        name:'深夜',
        img:require('@/assets/img/musicRadio/shenye.webp'),
        color:'#053561'
    },
    {
        id:977724604,
        name:'微醺',
        img:require('@/assets/img/musicRadio/weixun.webp'),
        color:'#b17baf'
    },
    {
        id:978246340,
        name:'R&B',
        img:require('@/assets/img/musicRadio/RB.webp'),
        color:'#223160'
    },
    {
        id:975689604,
        name:'说唱',
        img:require('@/assets/img/musicRadio/shuochan.webp'),
        color:'#9c6a56'
    },
    {
        id:962639630,
        name:'通勤',
        img:require('@/assets/img/musicRadio/tonqing.webp'),
        color:'#44836c'
    },
    {
        id:972469408,
        name:'摇滚',
        img:require('@/assets/img/musicRadio/yaogun.webp'),
        color:'#804041'
    },
    {
        id:959683623,
        name:'民谣',
        img:require('@/assets/img/musicRadio/minyao.webp'),
        color:'#537b92'
    },
    {
        id:526958705,
        name:'健身',
        img:require('@/assets/img/musicRadio/jianshen.webp'),
        color:'#777777'
    },
    {
        id:526813657,
        name:'治愈',
        img:require('@/assets/img/musicRadio/zhiyu.webp'),
        color:'#7aa6a2'
    },
    {
        id:526674744,
        name:'欧美',
        img:require('@/assets/img/musicRadio/oumei.webp'),
        color:'#3245b2'
    },
    {
        id:526912578,
        name:'电音',
        img:require('@/assets/img/musicRadio/dianyin.webp'),
        color:'#531b80'
    },
];

export default musicarr